name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Code
        uses: actions/checkout@v2
        
      - name: HTML
        uses: micmro/html-validator-action@v2
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
